spring:
  application:
    name: monday
#  datasource:
#    url: jdbc:postgresql://localhost:5432/student
#    username: student
#    password: student
  datasource:
    url: jdbc:h2:mem:students
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
server:
  port: 8081 #ustawiamy inny port, ponieważ działać będą dwie aplikacje